### PR TITLE
Suppression Resolution: List of Key-Value Maps

### LINKED ISSUE #1517: Resource Suppression: list of key-value map is not supported
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

### Description

The emitter is currently unable to handle sets of undefined, so if the resource schema includes this structure then generation will fail.

### Affected Resource(s)

- aws_scheduler_schedule (Target/EcsParameters/Tags)
- aws_omics_annotation_store (StoreOptions/TsvStoreOptions/Schema)

### Schema Definition

https://github.com/hashicorp/terraform-provider-awscc/blob/16665a71d7603c11674280216749948b03176180/internal/service/cloudformation/schemas/AWS_Scheduler_Schedule.json#L421-L471

https://github.com/hashicorp/terraform-provider-awscc/blob/16665a71d7603c11674280216749948b03176180/internal/service/cloudformation/schemas/AWS_Omics_AnnotationStore.json#L108-L124

### References

- #156

### PR DESCRIPTION
**Pull request by ThomasZalewski**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
* The resources and data sources in this provider are generated from the CloudFormation schema, so they can only support the actions that the underlying schema supports. For this reason submitted bugs should be limited to defects in the generation and runtime code of the provider. Customizing behavior of the resource, or noting a gap in behavior are not valid bugs and should be submitted as enhancements to AWS via the CloudFormation Open Coverage Roadmap.

Closes #1517 
Relates #156 

## Rollback Plan

If a change needs to be reverted, we will publish an updated version of the library.

## Changes to Security Controls

Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.

## Description

Added support in emitter.go for arrays of key-value maps. Part of the initiative to clear the AWSCC Provider's resource suppression error list.

```

terraform-provider-awscc % TF_LOG=ERROR make testacc PKG_NAME=internal/aws/logs TESTARGS='-run=TestAccAWSLogsLogGroup_\|TestAccAWSLogsLogGroupDataSource_' ACCTEST_PARALLELISM=3

TF_ACC=1 go test ./internal/aws/logs -v -count 1 -parallel 3 -run=TestAccAWSLogsLogGroup_\|TestAccAWSLogsLogGroupDataSource_ -timeout 180m
=== RUN   TestAccAWSLogsLogGroup_basic
=== PAUSE TestAccAWSLogsLogGroup_basic
=== RUN   TestAccAWSLogsLogGroup_disappears
=== PAUSE TestAccAWSLogsLogGroup_disappears
=== RUN   TestAccAWSLogsLogGroup_update
=== PAUSE TestAccAWSLogsLogGroup_update
=== RUN   TestAccAWSLogsLogGroupDataSource_basic
=== PAUSE TestAccAWSLogsLogGroupDataSource_basic
=== RUN   TestAccAWSLogsLogGroupDataSource_NonExistent
=== PAUSE TestAccAWSLogsLogGroupDataSource_NonExistent
=== CONT  TestAccAWSLogsLogGroup_basic
=== CONT  TestAccAWSLogsLogGroupDataSource_basic
=== CONT  TestAccAWSLogsLogGroupDataSource_NonExistent
2025-07-07T15:24:30.573-0700 [ERROR] sdk.proto: Response contains error diagnostic: diagnostic_severity=ERROR tf_proto_version=6.9 tf_rpc=ReadDataSource tf_data_source_type=awscc_logs_log_group tf_req_id=256c6221-dd5b-2898-ac50-6d719eb8b4b3 tf_provider_addr=registry.terraform.io/hashicorp/awscc diagnostic_summary="AWS Data Source Not Found" diagnostic_detail="After attempting to read the data source, the API returned a resource not found error for the id provided. Original Error: couldn't find resource"
--- PASS: TestAccAWSLogsLogGroupDataSource_NonExistent (1.59s)
=== CONT  TestAccAWSLogsLogGroup_update
--- PASS: TestAccAWSLogsLogGroupDataSource_basic (25.36s)
=== CONT  TestAccAWSLogsLogGroup_disappears
--- PASS: TestAccAWSLogsLogGroup_basic (28.87s)
--- PASS: TestAccAWSLogsLogGroup_update (41.01s)
--- PASS: TestAccAWSLogsLogGroup_disappears (32.47s)
PASS
ok      github.com/hashicorp/terraform-provider-awscc/internal/aws/logs
```

### CODE REVIEW

File: internal/provider/generators/shared/codegen/emitter.go [hunk 1]
```diff
@@ -393,56 +393,70 @@ func (e Emitter) emitAttribute(tfType string, attributeNameMap map[string]string
...
+					switch nestedPatternProperty.Type.String() {
+					case cfschema.PropertyTypeBoolean:
+						elementType = "types.ListType{ElemType: types.BoolType}"
+					case cfschema.PropertyTypeInteger:
+						elementType = "types.ListType{ElemType: types.Int64Type}"
+					case cfschema.PropertyTypeNumber:
+						elementType = "types.ListType{ElemType: types.Float64Type}"
+					case cfschema.PropertyTypeString:
+						elementType = "types.ListType{ElemType: types.StringType}"
+					}
```
Comment (jar-b) [inline internal/provider/generators/shared/codegen/emitter.go:414]: Should there be a default switch here to return if the type is none of those which are explicitly handled?

File: internal/provider/generators/shared/codegen/emitter.go [hunk 2]
```diff
@@ -393,56 +393,70 @@ func (e Emitter) emitAttribute(tfType string, attributeNameMap map[string]string
...
+				} else if len(property.Items.Properties) == 0 {
 					return features, unsupportedTypeError(path, "list of undefined schema")
```
Comment (jar-b) [inline internal/provider/generators/shared/codegen/emitter.go:416]: Nit - because this condition returns immediately, it might make sense to be the first thing checked rather than sandwiched between two larger blocks of if/else logic.

File: internal/provider/generators/shared/codegen/emitter.go (hunk 1 above)
Comment (ThomasZalewski) [reply internal/provider/generators/shared/codegen/emitter.go]: 👍 Agreed

File: internal/provider/generators/shared/codegen/emitter.go (hunk 2 above)
Comment (ThomasZalewski) [reply internal/provider/generators/shared/codegen/emitter.go]: Makes sense

File: internal/provider/generators/shared/codegen/emitter.go [hunk 3]
```diff
@@ -472,6 +484,22 @@ func (e Emitter) emitAttribute(tfType string, attributeNameMap map[string]string
...
+									/*
+										switch nested type
+
+
+									features.FrameworkValidatorsPackages = append(features.FrameworkValidatorsPackages, "mapvalidator") // get map validator package
+
+								} else {
+									return features, unsupportedTypeError(path, "list of unsupported object")
+								}
+						*/
```
[the remark this answers is not in the document]
Comment (ThomasZalewski) [reply internal/provider/generators/shared/codegen/emitter.go]: Removed!

File: internal/provider/generators/shared/codegen/emitter.go [hunk 4]
```diff
@@ -392,57 +392,73 @@ func (e Emitter) emitAttribute(tfType string, attributeNameMap map[string]string
...
+					// List of map
+					var nestedPatternProperty *cfschema.Property
+					for _, v := range property.Items.PatternProperties {
+						nestedPatternProperty = v
+						break
+					}
+					if nestedPatternProperty == nil {
+						return features, unsupportedTypeError(path, "list of key-value map with no pattern")
+					}
+					switch nestedPatternProperty.Type.String() {
```
Comment (jar-b) [inline internal/provider/generators/shared/codegen/emitter.go:407]: nit - some visual spacing to separate the nil check from the switch on pattern type.

```suggestion
					}

					switch nestedPatternProperty.Type.String() {
```

**Comment by ewbankkit** [comment]
#### Note to self

Once this PR is merged we need to add CHANGELOG entries for the corresponding release.

File: internal/provider/generators/shared/codegen/emitter.go [hunk 5]
```diff
@@ -392,57 +392,74 @@ func (e Emitter) emitAttribute(tfType string, attributeNameMap map[string]string
...
-					planModifiers = append(planModifiers, "generic.Multiset()")
+					switch arrayType {
+					case aggregateOrderedSet:
+						validators = append(validators, "listvalidator.UniqueValues()")
+						features.FrameworkValidatorsPackages = append(features.FrameworkValidatorsPackages, "listvalidator")
+					case aggregateMultiset:
+						planModifiers = append(planModifiers, "generic.Multiset()")
+					}
 				}
-
```
[the remark this answers is not in the document]
Comment (ThomasZalewski) [reply internal/provider/generators/shared/codegen/emitter.go:441]: Should be good! Let me know if there is anything else you see

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.
